version: '3'
services:
    mongo:
        image: mongodb/mongodb-community-server:latest
        command: --dbpath=/db
        volumes:
            - ./db:/db
        ports:
            - "127.0.0.1:27017:27017"
        container_name: ai_hack_db
        deploy:
            restart_policy:
                condition: on-failure
                delay: 2s

    mail_worker:
        build:
            context: ./mail_processor
            dockerfile: Dockerfile
        image: mail_worker
        volumes:
            - ./mail_processor:/app
        network_mode: host
        container_name: mail_worker
        environment:
            - MONGO_HOST=localhost
            - MONGO_PORT=27017
            - DB_NAME=ai_hack
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s

    telegram_bot:
        build:
            context: ./telegram_bot
            dockerfile: Dockerfile
        image: telegram_bot
        volumes:
            - ./telegram_bot:/app
        network_mode: host
        container_name: telegram_bot
        env_file:
            - .env
        environment:
            - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
            - MONGO_HOST=localhost
            - MONGO_PORT=27017
            - DB_NAME=ai_hack
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s

networks:
  host:
    name: host
    external: true