version: '3'
services:

    mongo:
        image: mongodb/mongodb-community-server:latest
        command: --dbpath=/db
        volumes:
            - ./db:/db
        ports:
            - "127.0.0.1:27017:27017"
        container_name: ai_hack_db
        deploy:
            restart_policy:
                condition: on-failure
                delay: 2s

    mail_worker:
        build:
            context: ./mail_processor
            dockerfile: Dockerfile
        image: mail_worker
        volumes:
            - ./mail_processor:/app
        network_mode: host
        container_name: mail_worker
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s

    app_logic:
        build:
            context: ./app_logic
            dockerfile: Dockerfile
        image: app_logic
        volumes:
            - ./app_logic:/app
        network_mode: host
        container_name: app_logic
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
        environment:
            - MONGO_LLM_INITDB_ROOT_USERNAME
            - MONGO_LLM_INITDB_ROOT_PASSWORD
            - MONGO_LLM_HOST
            - MONGO_LLM_INITDB_ROOT_PORT

    telegram_bot:
        build:
            context: ./tg_processor
            dockerfile: Dockerfile
        image: telegram_bot
        volumes:
            - ./tg_processor:/app
        network_mode: host
        container_name: telegram_bot
        environment:
            - TG_BOT_API_HASH
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s

networks:
  host:
    name: host
    external: true
